apiVersion: v1
kind: Pod
metadata:
  name: my-test-pod
spec:
  containers:
    - name: my-app
      image: my-app:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: my-app-config
      volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
  volumes:
    - name: logs-volume
      emptyDir: {}
